{% set version = "1.0-21" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-pspline
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/pspline_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pspline/pspline_{{ version }}.tar.gz
  sha256: 7f5739b9cf378dda6cd33d152b5f84ae2afa728f7dac0729dab565264138abca

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem            # [win]
    - {{ posix }}make
    - {{ posix }}sed                   # [win]
    - {{ posix }}coreutils             # [win]
    - {{ posix }}zip                   # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('pspline')"           # [not win]
    - "\"%R%\" -e \"library('pspline')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=pspline
  license: Unlimited
  summary: Smoothing splines with penalties on order m derivatives.
  license_family: OTHER
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
