# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangfortran_compilergfortran
    - CONFIG=osx_c_compilertoolchain_cfortran_compilertoolchain_fort

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "aDBwGA2DUgN/blgB2Yh6Gm3o9ZjhsZivsExyD7np/SCLTLsrokLRNoZBLQXB7v175zoDjoKmA3O+j2yx+FkEW0naV4OUrdlDLK3U7egLO5Xgf86eT7ffr/1fZ6k/VSDpxaaVCnsTsJju0yNTDhIzoS+UAscSS4u7sKKF/7BBd/m6J5QOm+4atTUacO/OWQL04Da3Tv5SrTVpxKhy0i2Mbx8+YbVIhcH0OSANF78Od1mvdq5bwG02ICK/mbwPvtVzkZoLdI6ixa8xlb4QLyWPPeSroMpnL1wpiWMz1+zEXdJY8T0KFKCzGTnu6J05ltsFp3jONIMcoQFYRuHwfQpVQHnOLNLLGijocJC5aojtxCtjjkBQpVXkAx3HgwLtR+HG+sOo8HvKipl1MZiTQMOwEoqdw0EHqwq9zAvMfeNwK1EeuLkgy0gj2VoqIz1Ix+N2rPzxlDzt3S5PE00qAWM3bPuOH4Q6H8+na1fSSRtJqod5JxkUfsmOuYikWVjP7q/po+OBQeIMVOxlm8NJFWjvKIWyTuk5gVoVTORl42syynPqB0Tj+hdQ6kBaGUrVKI19G84aA4yzuDKaUDf1uOpWg5vAfAUSXVzLOkqh2Dyg/oj7AIL+nJHHYyGsrii+8pyakOp15J135eNBIyVnfTNhG0jYCip7KCYDENTQkw6BTBk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
