appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: aDBwGA2DUgN/blgB2Yh6Gm3o9ZjhsZivsExyD7np/SCLTLsrokLRNoZBLQXB7v175zoDjoKmA3O+j2yx+FkEW0naV4OUrdlDLK3U7egLO5Xgf86eT7ffr/1fZ6k/VSDpxaaVCnsTsJju0yNTDhIzoS+UAscSS4u7sKKF/7BBd/m6J5QOm+4atTUacO/OWQL04Da3Tv5SrTVpxKhy0i2Mbx8+YbVIhcH0OSANF78Od1mvdq5bwG02ICK/mbwPvtVzkZoLdI6ixa8xlb4QLyWPPeSroMpnL1wpiWMz1+zEXdJY8T0KFKCzGTnu6J05ltsFp3jONIMcoQFYRuHwfQpVQHnOLNLLGijocJC5aojtxCtjjkBQpVXkAx3HgwLtR+HG+sOo8HvKipl1MZiTQMOwEoqdw0EHqwq9zAvMfeNwK1EeuLkgy0gj2VoqIz1Ix+N2rPzxlDzt3S5PE00qAWM3bPuOH4Q6H8+na1fSSRtJqod5JxkUfsmOuYikWVjP7q/po+OBQeIMVOxlm8NJFWjvKIWyTuk5gVoVTORl42syynPqB0Tj+hdQ6kBaGUrVKI19G84aA4yzuDKaUDf1uOpWg5vAfAUSXVzLOkqh2Dyg/oj7AIL+nJHHYyGsrii+8pyakOp15J135eNBIyVnfTNhG0jYCip7KCYDENTQkw6BTBk=}
bot:
  automerge: true
